FROM androidsdk/android-30

# Prerequisites
RUN apt update && apt install -y \
    curl \
    git \ 
    unzip \ 
    xz-utils \ 
    zip \ 
    libglu1-mesa \ 
    openjdk-11-jdk \
    wget \
    clang \
    cmake \
    ninja-build \
    pkg-config \
    libgtk-3-dev \
    apt-transport-https
# Install dart
RUN wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/dart.gpg
RUN echo 'deb [signed-by=/usr/share/keyrings/dart.gpg arch=amd64] https://storage.googleapis.com/download.dartlang.org/linux/debian stable main' | tee /etc/apt/sources.list.d/dart_stable.list
RUN apt update && apt install -y dart

# Install chrome
RUN wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apt update && apt  install -y ./google-chrome-stable_current_amd64.deb
ENV PATH "$PATH:/usr/lib/dart/bin"

# Set up new user
RUN useradd -ms /bin/bash developer
USER developer
WORKDIR /home/developer

# Download Flutter SDK
RUN git clone https://github.com/flutter/flutter.git
RUN cd flutter && git checkout 3.3.10 && cd ..
ENV PATH "$PATH:/home/developer/flutter/bin"

# Run basic check
RUN flutter doctor --android-licenses
RUN flutter doctor